stages:
  - build
  - test
  - review
  - stage
  - production

variables:
  DATABASE_URL: 'mongodb://mongo/user_posts'

before_script:   
  - cd reddit
  - apk add --update ruby-dev build-base libxml2-dev libxslt-dev pcre-dev libffi-dev 
  - gem install bundler
  - bundle update --bundler
  - bundle install

build_job:
  stage: build
  script:
    - echo 'Building'

#test_unit_job:
#  stage: test
#  services:
#    - mongo:latest
#  script:
##    - ruby simpletest.rb

test_integration_job:
  stage: test
  script:
    - echo 'Testing 2'

deploy_dev_job:
  stage: review
  script:
    - echo 'Deploy'
  environment:
    name: dev
    url: http://dev.example.com

staiging:
  stage: stage
  when: manual
  only:
    - /^\d+\.\d+\.\d+/
  script:
    - echo 'Deploy'
  environment:
    name: stage
    url: http://beta.example.com

production:
  stage: production
  when: manual
  only:
    - /^\d+\.\d+\.\d+/
  script:
    - echo 'Deploy'
  environment:
    name: prod
    url: http://www.example.com
