global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs: 
  - channel: '#george_klepach'
