version: '3.5'
services:
  post_db:
    image: mongo:${MONGO_VERSION}
    volumes:
      - post_db:/data/db
    networks:
      reddit_back:
        aliases:
          - post_db
          - comment_db
  ui:
    image: ${USERNAME}/ui:${UI_VERSION}
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
      - POST_SERVICE_HOST=post
      - POST_SERVICE_PORT=5000
      - COMMENT_SERVICE_HOST=comment
      - COMMENT_SERVICE_PORT=9292
    ports:
      - "9292:9292"
    depends_on:
      - post
    logging:
      driver: "fluentd"
      options:
         fluentd-address: localhost:24224
         tag: service.ui
    networks:
      - reddit_front

  post:
    image: ${USERNAME}/post:${POST_VERSION}
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
      - POST_DATABASE_HOST=post_db
      - POST_DATABASE=posts
    depends_on:
      - post_db
    ports:
      - "5000:5000"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post
    networks:
      - reddit_back
      - reddit_front
  comment:
    image: ${USERNAME}/comment:${COMMENT_VERSION}
    networks:
      - reddit_back
      - reddit_front

volumes:
  post_db:

networks:
  reddit_front:
    name: reddit_front_net
    driver: bridge
  reddit_back:
    name: reddit_back_net
    driver: bridge
