version: '3.3'
services:
  post_db:
    image: mongo:${MONGO_VERSION}
    volumes:
      - post_db:/data/db
    networks:
      reddit_back:
        aliases:
          - post_db
          - comment_db
  post:
    image: ${USERNAME}/post:${POST_VERSION}
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    ports:
      - "5000:5000"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post
    networks:
      - reddit_back
      - reddit_front
  comment:
    image: ${USERNAME}/comment:${COMMENT_VERSION}
    networks:
      - reddit_back
      - reddit_front

  ui:
    image: ${USERNAME}/ui:${UI_VERSION}
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    ports:
      - ${UI_PORT}:9292/tcp
    logging:
      driver: "fluentd"
      options:
         fluentd-address: localhost:24224
         tag: service.ui
    networks:
      - reddit_front

volumes:
  post_db:


networks:
  reddit_front:
  reddit_back:
