version: '3.5'
services:
  fluentd:
    image: ${USERNAME}/fluentd
    ports:
      - "24224:24224"
      - "24224:24224/udp"

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - reddit_front
      - reddit_back

  elasticsearch:
    image: elasticsearch:7.5.2
    expose:
      - 9200
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
      memlock:
        soft: -1
        hard: -1

  kibana:
    image: kibana:7.5.2
    ports:
      - "5601:5601"

networks:
  reddit_front:
  reddit_back:

